### PR TITLE
Add Support for Python 3

### PR DESCRIPTION
**Pull request by kendfinger**
Hi @brona, here is a PR for just Python 3 support.

Also, sorry about the fork, I was trying to get this up-to-date in Homebrew for Catalina and I forked the project thinking it was inactive, then I saw you merged the PRs :)

### CODE REVIEW

**Comment by brona** [comment]
Thanks no problem, I was about to spend some time on it this weekend. Anyway expect this one to be merged soon (I will release it likely as 1.3).

**Comment by kendfinger** [comment]
Awesome!

**Comment by kendfinger** [comment]
It's been a long time, any updates? I have a project that uses iproute2mac and we have a local fork that adds a lot of features to be able to support what I need. If you are able to accept PRs I'll start contributing those features soon.

**Comment by brona** [comment]
Sure, feel free to send PRs.

**Pull request merged**
