### PR TITLE
Added vlan and bridge management

### LINKED ISSUE #52: VLAN support
It is desirable to manage VLANs too as Linux does:
```shell
$ sudo ip link add link eth0 name eth0.111 type vlan id 111
$ sudo ip addr add 192.168.111.1/24 brd + dev eth0.111
$ sudo ip link set up dev eth0.111
$ ip addr show dev eth0.111
7: eth0.111@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether da:8d:21:53:7a:b5 brd ff:ff:ff:ff:ff:ff
    inet 192.168.111.1/24 brd 192.168.111.255 scope global eth0.111
       valid_lft forever preferred_lft forever
```

To show VLAN id in the output of `ip` command `-details` option is needed:
<pre>
$ ip -details addr show dev eth0.111
7: eth0.111@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether da:8d:21:53:7a:b5 brd ff:ff:ff:ff:ff:ff promiscuity 0  allmulti 0 minmtu 0 maxmtu 65535
    <b>vlan protocol 802.1Q id 111</b> <REORDER_HDR> numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 tso_max_size 65536 tso_max_segs 65535 gro_max_size 65536
    inet 192.168.111.1/24 brd 192.168.111.255 scope global eth0.111
       valid_lft forever preferred_lft forever
</pre>

In macOS could be translated into:
```shell
$ sudo ifconfig vlan111 create
$ sudo ifconfig vlan111 vlan 111 vlandev en0
$ sudo ifconfig vlan111 add 192.168.111.2/24
$ ifconfig vlan111
vlan111: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=3<RXCSUM,TXCSUM>
	ether 14:98:77:71:03:99
	inet 192.168.111.2 netmask 0xffffff00 broadcast 192.168.111.255
	vlan: 111 parent interface: en0
	media: 100baseTX <full-duplex>
	status: active
```

To remove the interface link (`ip link del eth0.111` in Linux) it is possible to use `ifconfig vlan111 destroy`.

There are some difference between macOS and Linux for VLAN interfaces:
1. in macOS the link is already UP (active) after the `ifconfig <interface> vlan <tag> vlandev <iface>` command;
2. it is impossible to set the link DOWN (inactive), `ifconfig <interface> down` has no effect;
3. in macOS interfaces cannot have a dotted notation as in Linux (e.g. en0.111):
```shell
$ sudo ifconfig en0.111 create
ifconfig: SIOCIFCREATE2: Invalid argument
```

### LINKED ISSUE #53: Bridge management
Simple bridge management in Linux is handled by iproute2 se follow:
```shell
$ sudo ip link add name br0 type bridge
$ sudo ip link set dev br0 up
$ sudo ip link set dev eth0 master br0
$ sudo ip link set dev eth1 master br0
```

To remove an interface from the bridge:
```shell
$ sudo ip link set dev eth0 nomaster
```

In macOS the same result can be obtained with:
```shell
$ sudo ifconfig bridge0 create
$ sudo ifconfig bridge0 addm en0
$ sudo ifconfig bridge0 addm en1
```

And to remove an interface from the bridge:
```shell
$ sudo ifconfig bridge0 deletem en0
```

Bridge interfaces must be named `bridge<n>`, otherwise the system will throw an exception:
```
$ sudo ifconfig br0 create
ifconfig: SIOCIFCREATE2: Invalid argument
```

### PR DESCRIPTION
**Pull request by signal-09**
Also added -details option to visualize additional link info (e.g. VLAN ID).

Closes #52
Closes #53

### CODE REVIEW

**Comment by brona** [comment]
Thank you for the contribution, I will look into it  during the weekend.

**Comment by brona** [comment]
Sorry for not getting to this sooner, I am now finishing the 1.5.0 release, https://github.com/Homebrew/homebrew-core/pull/179084, if you want we can get back to adding the VLANs once that is done.

**Comment by signal-09** [comment]
First of all, happy new release!
Don't worry, I started contributing to your project mainly to practice Python (I'm a beginner).
To avoid causing problems to others, accelerate my learning and also practice directly on CI/CD environments, I decided to rewrite the entire project bottom-up in an isolated environment few weeks ago (https://github.com/signal-09/iproute4mac/).
Feel free to reuse anything you think might be useful for your project (also suggestions are welcomed).

**Comment by signal-09** [comment]
> Btw see recent commits, there were two bugs in your parse_ifconfig implementation.

I see. Thank you for prompt fixing it.

I worked a lot (as exercise) to reproduce the iproute2 skeleton and UI look&feel in my separated experiment (https://github.com/signal-09/iproute4mac/). On the `ip` side I suspect I have reach a sort of feature parity with your project, and some extensions like `bond`, `bridge`, `vlan`, and `feth` (the macOS semi undocumented implementation of Linux `veth`).

To enforce the code writing style [flake8](https://flake8.pycqa.org/en/latest/) where used, then switched to [ruff](https://docs.astral.sh/ruff/), in addition to an embryonic version of pytest for functionality checks.

Most IPv4 & v6 logic where migrated to a Prefix object, derived form `ipaddress`; so to be able to translate `iproute2` filtering (.e.g. `to`, `from`, `match`) with Python native operations (`__eq__`, `__contain__`, `set() <= set()`). My idea is to do the same with back-end commands (`ifconfig`, `netstat`, `route`, etc.) in some future release.

Also tried to imitate exactly the JSON output of `iproute2` that, as you already know, is not fully JSON compliant... but that's it.

Needless to say, any kind of input from you is very very appreciated.

**Pull request closed without merging**
