### PR TITLE
Fix `ip route` for macOS Catalina issue #30

### PR DESCRIPTION
**Pull request by jiegec**

### CODE REVIEW

**Comment by jiegec** [comment]
Other commands seems working properly: `ip l` and `ip a`

**Comment by littleya** [comment]
Great :)

**Comment by vlcty** [comment]
@brona *ping*

**Comment by kendfinger** [comment]
Due to inactivity, I've forked the project and am trying to get it into Homebrew.

https://github.com/SpinlockLabs/iproute2mac

I've included your fix.

**Comment by brona** [comment]
> @brona _ping_

Thanks for the ping, I had my email notifications configured somehow wrong, releasing new version.

**Comment by vlcty** [comment]
Thank you very much!

**Pull request merged**
